language: python
python:
  - 3.7.6
services: 
  - docker
install: 
  - docker pull yuxio/ffp
  - docker build -t yuxio/ffp .
  - docker run -d --name=ffp -p 127.0.0.1:502:80 --restart=always yuxio/ffp:latest
before_script:
  - pip install -r requirements.txt
  - pip install pytest
script:
  - docker ps | grep -q yuxio/ffp
  - pytest